language: node_js

node_js:
  - 'stable'

install:
  - npm install

script:
  - tsc -p ./
  - tslint --project tsconfig.json -e src/*.d.ts --type-check -t verbose

notifications:
  email:
    on_success: never
    on_failure: always
