/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { type SiteConfig } from "@azure/arm-appservice";
import { type DomainNameLabelScope } from "@microsoft/vscode-azext-azureappservice";

export interface SiteInterim {
    name?: string;
    kind?: string;
    location?: string;
    extendedLocation?: {
        name?: string;
        type?: string;
    };
    properties?: SitePropertiesInterim;
}

export interface SitePropertiesInterim {
    autoGeneratedDomainNameLabelScope?: DomainNameLabelScope;
    clientAffinityEnabled?: boolean;
    reserved?: boolean;
    serverFarmId?: string;
    siteConfig?: SiteConfig;
}
