import { type SiteConfig } from "@azure/arm-appservice";

export enum DomainNameLabelScope {
    Tenant = 'TenantReuse',
    Subscription = 'SubscriptionReuse',
    ResourceGroup = 'ResourceGroupReuse',
    Global = 'NoReuse',
}

export interface SiteInterim {
    name?: string;
    kind?: string;
    location?: string;
    extendedLocation?: {
        name?: string;
        type?: string;
    };
    properties?: SitePropertiesInterim;
}

export interface SitePropertiesInterim {
    autoGeneratedDomainNameLabelScope?: DomainNameLabelScope;
    clientAffinityEnabled?: boolean;
    reserved?: boolean;
    serverFarmId?: string;
    siteConfig?: SiteConfig;
}
